### ISSUE TITLE
Noob cant understand how to use your tool

### ISSUE THREAD

**Issue by nicholasjb89** [nistur/bod2obj#9]
Thank you for making this tool to help extract the ship files from x3 to .obj for printing. I however must not have the technical skills to understand your Readme. 

1) I do not understand where the file bin/bod2obj.exe is. Do I need to compile the src code to use this? 
2) your instructions are "make bin/bod2obj.exe path/to/argon_m3.bod ArgonNova". I do not see a file named make? 

I have some time programming in python but for the life of me there must be something im missing. If you could help me out and give me a little more info on how to use your tool that would be great thank you.

Nick the perpetual noob.

**Comment by nistur** [comment]
You do need to compile the source at the moment. I have been using mingw/msys2 up to now when testing on Windows.

Make is GNU make, and used for compiling, not for running. 

I'll make a release tonight and push up some executables for Windows, Linux, and macOS. You should just be able to use those then.

**Comment by nistur** [comment]
@nicholasjb89 Try downloading from [v0.1](https://github.com/nistur/bod2obj/releases/tag/v0.1)

**Comment by nicholasjb89** [comment]
I'm sorry it took so long to get back to you. I honestly did not think you would respond haha. 

Thank you so much though. This was exactly what I needed. You even made it noob-friendly by dragging and dropping right on the exe. You have saved me a lot of trouble trying to figure out how to use the YAGG program with Gmax. 2+ hours later I could never really get it to work.

Just so you know I really wanted this for the Argon Centaur Ship. It was my favorite ship when I was playing X3 Reunion. Ill be trying to 3D print it. good luck to me! haha

Thanks again though. This was hugely helpful to me.

**Comment by nistur** [comment]
No problem. I'm happy it's of use to someone :) 

Using Gmax is a pain, and nobody should be put through that!

Good luck with the Centaur. I've not printed anything that large, so I cannot advise. The centaur doesn't have hanger bays by the look of it, so it should be fairly straightforward, you might be missing turrets however, as they're defined separately and instanced around the ships. I haven't got around to handling the ship scene files that would pull these additional models in yet.
